d6_11/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from allauth.account.views import login, logout, signup
from p_library import views


urlpatterns = [
    path("p_library/", include("p_library.urls", namespace="p_library")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", views.home, name="app_root"),    
    path('login/', login, name='login'),  
    path('logout/', logout, name='logout'),
    path("register/", signup, name="register"),
    path("profile-create/", views.CreateUserProfile.as_view(), name="profile-create"),
    path('index/', views.indexL.as_view()),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path("pubs/", views.pubs),    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin  
from django.urls import path  

from . import views
  
app_name = 'p_library'  
urlpatterns = [  
    path('author/create', views.AuthorEdit.as_view(), name='author_create'),  
    path('authors', views.AuthorList.as_view(), name='authors_list'),
    path('author/create_many', views.author_create_many, name='author_create_many'),
    path('author_book/create_many', views.books_authors_create_many, name='author_book_create_many'),
    path('friend/create', views.FriendEdit.as_view(), name='friend_create'),  
    path('friends', views.FriendsList.as_view(), name='friends_list'),
    path("lended", views.lended),
    path("lend_return", views.lend_return),
    path("do_lend_return/", views.do_lend_return),        
]

p_library/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from allauth.socialaccount.models import SocialAccount

# Create your models here.


class UserProfile(models.Model):    
    socacc = models.OneToOneField(SocialAccount, on_delete=models.CASCADE, verbose_name="Social account")
    user = models.OneToOneField(User, on_delete=models.CASCADE)    


class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    def __str__(self):
        return "{}, {}".format(self.full_name, self.birth_year)


class Publisher(models.Model):
    name = models.TextField(unique=True)

    def __str__(self):
        return self.name


class Friend(models.Model):
    name = models.TextField()
    
    def __str__(self):
        return self.name


class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=30, decimal_places=2)
    publisher = models.ForeignKey(Publisher, null=True, blank=True, on_delete=models.CASCADE)
    lendedto = models.ForeignKey(Friend, null=True, blank=True, on_delete=models.CASCADE)
    cover = models.ImageField(upload_to="covers", blank=True)

    def __str__(self):
        return self.title

p_library/forms.py
from django import forms  
from allauth.socialaccount.models import SocialAccount
from p_library.models import Author, Book, Friend, UserProfile
  
class AuthorForm(forms.ModelForm):

    full_name = forms.CharField(widget=forms.TextInput)

    class Meta:  
        model = Author  
        fields = '__all__'


class BookForm(forms.ModelForm):  
    class Meta:  
        model = Book  
        fields = '__all__'


class FriendForm(forms.ModelForm):  

    name = forms.CharField(widget=forms.TextInput)

    class Meta:  
        model = Friend  
        fields = '__all__'


class ProfileCreationForm(forms.ModelForm):  
  
    age = forms.IntegerField()

    class Meta:  
        model = UserProfile
        fields = []

p_library/views.py
import uuid
from django.shortcuts import render, redirect

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.views.generic import CreateView, ListView, FormView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.core.exceptions import ObjectDoesNotExist
from allauth.socialaccount.models import SocialAccount
from p_library.models import Book, Publisher, Author, Friend, UserProfile
from p_library.forms import AuthorForm, BookForm, FriendForm, ProfileCreationForm


def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)


def get_context(request):
    context = {}
    if request.user.is_authenticated:
        context["username"] = request.user.username
        context["provider"] = SocialAccount.objects.get(user=request.user).provider
        context["age"] = SocialAccount.objects.get(user=request.user).extra_data["age"]
        if context["provider"] == "github":
            context['github_url'] = SocialAccount.objects.get(user=request.user).extra_data['html_url']
    return context


def home(request):
    try:
        context = get_context(request)
    except ObjectDoesNotExist:
        context = {}    
    template = loader.get_template('home.html')        
    return HttpResponse(template.render(context))


class CreateUserProfile(FormView):  

    form_class = ProfileCreationForm  
    template_name = 'profile-create.html'  
    success_url = reverse_lazy('app_root')  

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('login'))  
        return super(CreateUserProfile, self).dispatch(request, *args, **kwargs)  

    def form_valid(self, form):  
        instance = form.save(commit=False)  
        instance.user = self.request.user  
        instance.socacc, created = SocialAccount.objects.get_or_create(user=instance.user, defaults={"provider": "local", "uid": uuid.uuid1()})
        instance.socacc.extra_data["age"] = form.cleaned_data["age"]
        instance.socacc.save()
        if created:
            instance.save()  
        return super(CreateUserProfile, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        try:
            context.update(get_context(self.request))
        except KeyError:
            pass
        except ObjectDoesNotExist:
            pass
        return context

    def get_initial(self):    
        initial = super().get_initial()        
        try:            
            initial['age'] = get_context(self.request)["age"]
        except KeyError:
            pass
        except ObjectDoesNotExist:
            pass
        return initial


def index(request):   
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    template = loader.get_template('index.html')    
    books = Book.objects.all()
    biblio_data = {
        "title": "мою библиотеку",        
        "books": books,        
    }
    biblio_data.update(get_context(request))
    return HttpResponse(template.render(biblio_data, request))


class indexL(ListView):    
    model = Book    
    context_object_name = "books"
    template_name = "index.html"     

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('login'))  
        return super(indexL, self).dispatch(request, *args, **kwargs)     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_context(self.request))
        return context


def book_increment(request):
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def book_decrement(request):
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')



def pubs(request):    
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    template = loader.get_template('pubs.html')    
    pubs = Publisher.objects.all()
    pub_data = {
        "pubs": pubs,
    }
    pub_data.update(get_context(request))
    return HttpResponse(template.render(pub_data, request))


class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    success_url = reverse_lazy('p_library:authors_list')  
    template_name = 'authors_edit.html'

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('login'))  
        return super(AuthorEdit, self).dispatch(request, *args, **kwargs)     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_context(self.request))
        return context


class AuthorList(ListView):  
    model = Author  
    template_name = 'authors_list.html'

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('login'))  
        return super(AuthorList, self).dispatch(request, *args, **kwargs)     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_context(self.request))
        return context


def author_create_many(request):  
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:authors_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})


def books_authors_create_many(request):  
    if request.user.is_anonymous:
         return HttpResponseRedirect(reverse_lazy('login'))
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  
    BookFormSet = formset_factory(BookForm, extra=2)  
    if request.method == 'POST':  
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')  
        if author_formset.is_valid() and book_formset.is_valid():  
            for author_form in author_formset:  
                author_form.save()  
            for book_form in book_formset:  
                book_form.save()  
            return HttpResponseRedirect(reverse_lazy('p_library:authors_list'))  
    else:  
        author_formset = AuthorFormSet(prefix='authors')  
        book_formset = BookFormSet(prefix='books')  
    return render(
	    request,  
		'manage_books_authors.html',  
		{  
	        'author_formset': author_formset,  
			'book_formset': book_formset,  
		}  
	)


class FriendEdit(CreateView):  
    model = Friend
    form_class = FriendForm  
    success_url = reverse_lazy('p_library:friends_list')  
    template_name = 'friends_edit.html'

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            return HttpResponseRedirect(reverse_lazy('login'))  
        return super(FriendEdit, self).dispatch(request, *args, **kwargs)     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_context(self.request))
        return context


class FriendsList(ListView):  
    model = Friend  
    template_name = 'friends_list.html'

    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  

p_library/templates/authors_edit.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - создание автора.
{% endblock extra_header %}

{% block main_content %} 

	<form method="post">  
		{% csrf_token %}  
		{{ form.as_p }}  
		<input type="submit" value="Сохранить" class="btn btn-info btn-sm btn-block">  
	</form>  

{% endblock main_content %} 

p_library/templates/authors_list.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - список авторов.
{% endblock extra_header %}

{% block main_content %}    

	<ul class="list-group md-auto">
		{% for author in object_list %}
		    <li class="list-group-item colbg">{{ author.full_name }}</li>
		{% endfor %}
	</ul>

{% endblock main_content %}    

p_library/templates/friends_edit.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - создание друга.
{% endblock extra_header %}

{% block main_content %} 

<form method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить" class="btn btn-info btn-sm btn-block">  
</form>  

{% endblock main_content %} 

p_library/templates/home.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - меню.
{% endblock extra_header %}

{% block main_content %}    
{% if username %}
    <div class="wrapperin">            
        <a href="index/" class="btn btn-primary btn-sm btn-block">Индекс</a>            
        <a href="pubs/" class="btn btn-primary btn-sm btn-block">Издательства</a>            
        <a href="p_library/authors" class="btn btn-primary btn-sm btn-block">Авторы</a>            
        <a href="p_library/author/create" class="btn btn-primary btn-sm btn-block">Создание автора</a>                    
        <a href="p_library/friends" class="btn btn-primary btn-sm btn-block">Друзья</a>            
        <a href="p_library/friend/create" class="btn btn-primary btn-sm btn-block">Создание друга</a>            
        <a href="p_library/lended" class="btn btn-primary btn-sm btn-block">Одолженные книги</a>            
        <a href="p_library/lend_return" class="btn btn-primary btn-sm btn-block">Одолжить или вернуть книгу</a>            
    </div>    
{% else %}
<div class="wrapperin">            
    <a href="login/" class="btn btn-primary btn-sm btn-block">Вход</a>    
</div>   
{% endif %}
{% endblock main_content %}

p_library/templates/index.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - список книг.
{% endblock extra_header %}

{% block main_content %}    

<div class="wrapperin">
    Добро пожаловать в мою библиотеку. <br>
    Тут собрано {{ books|length }} книг из моей личной коллекции.

    <table border="1">
        {% for book in books %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>
                {% if book.cover %}
                    <img src="{{ book.cover.url }}" height="90" width="60">
                {% endif %}
            </td>
            <td>{{ book.title }}</td>
            <td>{{ book.ISBN }}</td>
            <td>{{ book.description }}</td>
            <td>{{ book.year_release }}</td>
            <td>{{ book.author.full_name }}</td>
            <td>{{ book.author.country }}</td>
            <td>{{ book.copy_count }}</td>
            <td>
                <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <input type="submit" value="Увеличить кол-во" class="btn btn-info btn-sm btn-block mb-1" />
                </form>
                <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{book.id}}" />
                    <input type="submit" value="Уменьшить кол-во" class="btn btn-info btn-sm btn-block" />
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock main_content %}

p_library/templates/lend_return.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - одолжить или вернуть книгу.
{% endblock extra_header %}

{% block main_content %} 
   
<div class="wrapperin">
    <table border="1">
        <tr>
            <td></td>
            <td>Обложка</td>
            <td>Название</td>                
            <td>Год</td>
            <td>Автор</td>           
            <td>Кому одолжена</td>         
            <td>Действие</td>
        </tr>
        {% for book in books %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>
                {% if book.cover %}
                    <img src="{{ book.cover.url }}" height="90" width="60">
                {% endif %}
            </td>
            <td>{{ book.title }}</td>                
            <td>{{ book.year_release }}</td>
            <td>{{ book.author.full_name }}</td>   
            {% if book.lendedto == None %} 
                <td>Не одолжена</td>
                <td>
                    <form action="/p_library/do_lend_return/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{book.id}}" />
                        <input type="submit" value="Одолжить" class="btn btn-info btn-sm btn-block mb-1" />
                        
                        <label for="friendselect">Кому:</label>
                        <select name="fid" id="friendselect">
                        {% for friend in friends %}
                        <option value="{{friend.id}}">{{friend.name}}</option>                      
                        {% endfor %}
                        </select>                    
                    </form>
                </td>
            {% else %}
                <td>{{ book.lendedto.name }}</td> 
                <td>
                    <form action="/p_library/do_lend_return/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{book.id}}" />
                        <input type="submit" value="Вернуть" class="btn btn-info btn-sm btn-block mb-1" />
                    </form>                
                </td>
            {% endif %}               
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock main_content %} 

p_library/templates/lended.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - одолженные книги.
{% endblock extra_header %}

{% block main_content %} 

    <table border="1">
        <tr>
            <td></td>
            <td>Обложка</td>
            <td>Название</td>
            <td>Кому одолжена</td>            
        </tr>
        {% for book in lends %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>
                    {% if book.cover %}
                        <img src="{{ book.cover.url }}" height="90" width="60">
                    {% endif %}
                </td>
                <td>{{ book.title }}</td>
                <td>{{ book.lendedto }}</td>            
            </tr>		
        {% endfor %}	
    </table>

{% endblock main_content %} 

p_library/templates/login.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - вход.
{% endblock extra_header %}

{% block main_content %}    
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_ul }}  
        <input type="submit" value="Войти">  
    </form>   
{% endblock main_content %}

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple authors</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{{ author_formset.management_form }}
	{% for form in author_formset %}  
		{{ form.as_ul }}  
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple Authors and Books</title>  
</head>  
<body>  
<form method="post">  
  {% csrf_token %}  
  {{ author_formset.management_form }}
  {% for form in author_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
  
  {{ book_formset.management_form }}
  {% for form in book_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/pl_base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
{% load socialaccount %}
<head>
    <meta charset="utf-8">
    <title>Личная библиотека.</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
</head>

<body>
    <header>
        <div class="wrapperout">
            <div class="wrapperheader">
                <h1>Сайт личной библиотеки{% block extra_header %}{% endblock extra_header %}</h1>
                {% if username %}
                <p>Привет, {{ username }} с адресом {% if provider == "local" %} {{ provider }} {% else %} {{ github_url }} {% endif %} в возрасте {{ age }}</p>
                {% else %}
                <p>Тебе нужно <a href="register/">зарегистрироваться</a> или <a href="login/">войти на сайт</a>!</p>
                {% endif %}
            </div>
        </div>
    </header>
    <main>
        <div class="wrapperout">
            {% block main_content %}
            {% endblock main_content %}
        </div>
    </main>
    <footer>
        <div class="wrapperout">       
            <div class="wrapperin footer">
                <a href="/" class="btn btn-primary btn-sm btn-block">Меню</a>
                {% if username %}
                <a href="/profile-create/" class="btn btn-primary btn-sm btn-block">Заполнение профиля</a>
                <a href="/logout/" class="btn btn-primary btn-sm btn-block">Выйти</a>
                {% endif %}
            </div>
        </div>
    </footer>
</body>

p_library/templates/profile-create.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - создание профиля.
{% endblock extra_header %}

{% block main_content %}    
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_ul }}  
        <input type="submit" value="Создание профиля">  
    </form>   
{% endblock main_content %}

p_library/templates/pubs.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - список издательств и их книг.
{% endblock extra_header %}

{% block main_content %} 

<div class="container d-flex flex-column justify-content-between">
    <div class="flex-md-equal mt-5">
        {% for pub in pubs %}
            <div class="mb-5">
                <p class="h4">Книги издательства "{{pub.name}}":</p>
                <ul class="list-group md-auto">
                {% for book in pub.book_set.all %}
                    <li class="list-group-item colbg">{{book.title}}</li>
                {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock main_content %} 

p_library/templates/register.html
{% extends 'pl_base.html' %}

{% block extra_header %}
    - регистрация.
{% endblock extra_header %}

{% block main_content %}    
    <form method="post">  
        {% csrf_token %}  
        {{ form.as_ul }}  
        <input type="submit" value="Зарегистрироваться">  
    </form>   
{% endblock main_content %}